title = "LATYNKA.TAK"
description ="Осідок української латинки у мережжі"
baseURL = "https://latinca.umova.top"
languageCode = "uk-UA"
DefaultContentLanguage = "uk"
publishDir = "docs"
theme = "laty01"
copyright = "2014 – LATYNKA.TAK"
favicon = "/img/favicon.ico"


[params]
# In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be uselgitess.
google_analytics_id = ""
google_tag_manager_id = ""

[taxonomies]
category = "categories"
tag = "tags"
year = "year"
sourcename = "sourcename"
sourcelink = "sourcelink"
sourcejustname = "sourcejustname"
latinica = "latinica"


[menu]
# Main Menu
[[menu.main]]
name = "Дописи"
url = "/publikaciji/"
weight = 1

[[menu.main]]
name = "Снутки"
url = "/projekty/"
weight = 2

[[menu.main]]
name = "Книги"
url = "/biblioteka/"
weight = 3

[[menu.main]]
name = "LatTexty"
url = "/lattexty/"
weight = 4


# Footer Menu
[[menu.footer]]
name = ""
url = "/"
weight = 1



